artifact_location: /Workspace/Users/rcoundinya@gmail.com/stockout-prediction-mlops/tracking-runs/797173910681765182
creation_time: 1768904533377
experiment_id: '797173910681765182'
last_update_time: 1768904533377
lifecycle_stage: active
name: stockout-mlops-local
